DEBUG: True
SECRET_KEY: g&*0o49mk(t&*vvdsfsdgfsdgsgesqdg5n*e7ars&$qz*lpi^s$k*
ALLOWED_HOSTS:
    - localhost
    - 127.0.0.1
    - 0.0.0.0

CORS_ALLOWED_ORIGINS:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost:8000"
    - "http://127.0.0.1:8000"
CORS_ALLOW_CREDENTIALS: true

MAIN_URL: http://127.0.0.1:8000/

DATABASE_HOST: db
DATABASE_NAME: tournesol
DATABASE_USER: tournesol
DATABASE_PASSWORD: password

STATIC_ROOT: /tournesol/static
MEDIA_ROOT: /tournesol/media/

ACCESS_TOKEN_EXPIRE_SECONDS: 36000 # 10h
REFRESH_TOKEN_EXPIRE_SECONDS: 604800 # 1w
LOGIN_URL: /admin/login
OIDC_ENABLED: true
OIDC_ISS_ENDPOINT: http://127.0.0.1:8000/o
# openssl genrsa 4096
OIDC_RSA_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKAIBAAKCAgEAx0m1CHyJjkjCQW3f9pRDXHDWkmJtEGTPLqoxug8TRi6baRKs
    H+6nbBeissoyviCdtMGQ+R+pdJH9NPjXpIh3siKeW8Wun0VZAR3+KciF+GpPr31Y
    NJU12QN2+c8Mxihza5Cc1OQfFwiO3ORkO+/xWlAYEILcAHKsHdYfwZXeaX9/X0uJ
    hLtYehmjZFe3K6J1rSdon/DoAlpAoiolrpOUxnUUlsXr0vEUxmZJbBpx/fXYiSv9
    MiGQ5RNyuyjrg0UxzBIKqaFdmFGfeF0ENTtvbaDpIb+gtPmfGo/+YHkEurcxPViF
    kY5pphDy+rhF0cjCUNMJGwrnpWGCEH8eOraPV4+1V6hIT0bS37XZ6dIgc9++27pl
    qgZgIbq7ueSGPUnF34p9qvEP43UsGCugVTeB9eq0ySdKf5xjHB+xb9D3fgMHlzDo
    tTy89J/UiDmM7a/m4ZY63LkGsJpiA3QwNobA81jYJosTbKw8bGI6tvFBZryNHaVb
    EnCuWvgqaNR87oR7eu2hCuGfmZ618hnepLb2B73ALhraB+GUE34/clvJP+hIMoJG
    HTQYkKgoZFoCXhI4uWcNntK0AcbvjAaAL9gh7L8xl1Eg3NNzx0/Xel+GuKPF8ms+
    15MS8wuiC6ohNkA7W6JNDKWj/SLDA90Q2NJ37IVgdYtbIao4LGGm3k6JoNkCAwEA
    AQKCAgB0Dctb/tJIRrzBR5AWU28K5Tc/lgv3cQ1qGnjM5jyOMVQVk2cjTWK4Qudf
    gPqd1/afLd4UBckz9lRjRcqmqUYzOY/I180COWtEiEfb40eJS7fN9YupS39JOohN
    n7LLrwDQEi4SmCo2yqgPoP1yHiAKPPxWmS4vIJh0454oqPMVssblIuMZpdQ3fri1
    FZO42Gn5BSsbgTpLLG3ZQfwhtxX7oHD2AJp9hCFaDHUTfC8H+uQ3taNET2HG1VWK
    AqFsF56RPaxx7mPH8TiR6nEp4svYJs289pBK89cgq9wyKCeF6GrHU8as5idGKzak
    pS0bpvLqCIuT8PzHRYptuulKvceo6epGS3Nv4kdFheqJ1QEQ0HAsqrOhXw7X8JzG
    18DEd15D82aU0sjDJGDjZ1Ja0EGjNzqwKFRpML/rzEq/Lg/QEh3Gl7p4LWxGKmfS
    9pscugXPQ2EP04Ee8OpyCKxNp/ZEIkWeqL8dhWpZDJvwhyJEyZRg/EhPzE2OphhT
    Eusnt4z9g0dm8SuZRo0dah5yGw5OKVGtb7sb/atVFIHdj5TjdSu4+ZLNbkjxUfMn
    6xrpSlnd+SXGL9RUs+xvJFHqfSt0TwkdyWxNwocHRa2NPBTmPr6PZA2LFCmq6F6t
    lr9r+kGdLJmSuuX0cmWIhPXiIxt503v7iSBgKFAbO0rhDx5aRQKCAQEA6lS3EwgV
    Bxn1U3yaqw338tSXxOEAwAstbyt5/uI/NGRs8rrckWz12ThRv8G3zDzhUZu3bqlE
    AU4NFxyYYEdAWJPedC5xPvvlZFWkpFfznLYvTarIIblP1/WPpXyvHwjxhDeNd1Ot
    5xNo5CVIrDokGm745GvgVmuA04ZNPTvSZfi/scBLHPliiDv6qAV9jlEvFdPJvizz
    a64x0lmaPT6pylUcmDYQI0gQTokk5Rmlw0F1m87rKlTiL0O5FRD8YHQqqlubOfPU
    fP+Q8bgWcGcYar8OPs5X6JfJ0OrddL9ekcCp1SCkKgfQWuMAf39IHJpAHo5J+cGs
    cgyYG+H2cWZHzwKCAQEA2bdsePyCyb73ngd6m7hXHeiIv11kzfC4i+YqalXTdjcN
    fxD4O+aHbfoz2YJDHZrZTzaMCwKa8rzqaHAPW2Q4sG39DUsnJF4QJZTlAIKAnhAs
    7RL3e4F+cpQ/5Ub2Ww/UpM9HBOm9i7kQwQNtIrMbFel1Fmim3BQGn9QUihXms24+
    3vu7ld20g66hDDovbsbtQEwGjUbLuvHuJh6XTmy65tZ2egMElieXHeZq6gpUZS//
    G1ftYVjH8p7FNRTQ21XuSC47jinaFRoiw1K36RKA3dfxbj4aTQfomaqCiPr7RKXN
    WT7mKzvNh2Fn0ttnNbezlfv1iZBvIYKB7lOd4moO1wKCAQAtv8paWdqZH1VJLmuX
    98svypey5WbbF5OQP8G6pHtIhE7M+PR1I/u/pAI52N1Eb6Jh52/hmARh6NYfbALH
    0UFbycrFjgeoD0/SzfGt8Ensj5kepbga9W4EMLoRygz6lyln8dyZrmmmUqDI4gqV
    LWi9DGtlVTZgSO7G3VKZIOPL6suqLWu8xWeaR3OBeEjyDyGNNmMN0QLZRBIQClRV
    nrVRflpt0ShHaxtb6eSdIeu9+jq256f8BMSAC83HsiBDyIpH5kihANy8ZrzqpFEl
    MsuOk6x5UJnTHEdXlXMVBwO0mxPNO2kxl4LzK5x+R+BRTUA1dvw0Wb6MKa9Myknu
    C9T7AoIBAQCTLSLf+tszJKxhoO6qfAgwSLTAoJL3gMZQlGyR66kCnh66ii801xcw
    KlaIsD1MsxQ6L0amXsF+XGUd6rsG7g5Afmn1ZZt1Qz0pGqlgGdh2gbrNHOg+DoD7
    VeqHxNvfHSmDrDd3Q8eFv7pqsDVDos4pluM3HdHGrqb3vrePzVRicaGAva3GltRj
    vFZUXLUZ7tINiBdZw8UPgGKcVEu2kVwbllkLDCU6mFLYvJ4Dzq3UpYiP5HWtPAYW
    pmvsAUFbNJDbLJ3H8dTiNQPRBIccwQxqa4NjIgpHjpQX5SNPFFNtyaOytAmGqmu7
    HAbCjN0NfDyjpGsM7p2hiobpJI9zsnyLAoIBAEHZJuG7GY9VUqr5JSBHK4oL9eis
    aeLyPc86JAejaSc0BoLFfgoreP6ukinBOZQauu3vBwJto9fMg1oick4egFtgmO3V
    y3d0HX4EH8Llp8SXr8/2LbdS+qG5AiUy4Hm6t2+ELBZBaCWgBaE4a5SCnIFqHKYK
    Y0e2LHZzlM7sT3G/om7huT4bn63J0TCswikrFFvGMIdaqGRWMRfY0sJtYvsMRyVv
    DKjJVdi7rR3AhYtXzoKx3aTLhe+R9LgL0MTkUpYFUM8IrQYuKlwQYIupJJdVVd9m
    sLthP2MuAwh4023RZrBLy2rNd2pmqtIYvH7vj98rgQmkTirGr0zFEHb4uEA=
    -----END RSA PRIVATE KEY-----


SWAGGER_UI_OAUTH2_CLIENT_ID: vY17xBi0MZKZCotrfma5ympAd0hq30OudU78HZAY
SWAGGER_UI_OAUTH2_CLIENT_SECRET: ZJ5FZeHomIgq6uNpVgNKwJiXDfFZz1HijDhsQJlXXnFKF6R7bUqc49Dv5MNL3cYTUrE1axrTtJTSr6IkHCc417ye8bLR8facpmhD4TwQqg7ktIQ047Y2Xp0rRcKLlIvq
