name: Continuous Integration

on:
  push:
    branches-ignore:
      - dev-server
  pull_request:
    branches-ignore:
      - dev-server

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: local-fix
        run: |
          # Hack to get setup-python to work on act
          # (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" | sudo tee /etc/lsb-release
          fi
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run install script
        run: ./setup.sh
      - name: Run all tests
        run: |
          source venv-tournesol/bin/activate
          ./tests.sh
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: integration-test-video
          path: integration_test/*.avi
